finished US12 and US13
scolicodes/CS-555-Project pull request #12
Opened 2023-07-12 21:29 UTC by scolicodes

2023-07-12 22:47 UTC, RonnieArvanites requested changes

2023-07-12 22:47 UTC, RonnieArvanites commented on USTests.py
>      Author: Your Name
@scolicodes Should Author be set to your name?

2023-07-13 00:40 UTC, RonnieArvanites approved these changes

2023-07-17 22:14 UTC, Slackow approved these changes

2023-07-17 22:14 UTC, merged