Us 35 36
scolicodes/CS-555-Project pull request #21
Opened 2023-08-09 21:13 UTC by scolicodes

2023-08-09 21:29 UTC, Slackow requested changes

2023-08-09 21:29 UTC, Slackow commented on GEDCOMReader.py
> +        birth_date = datetime.strptime(individual.birthday, '%d %b %Y')
you should replace these datetime calls with the `to_date` function

2023-08-09 21:29 UTC, Slackow commented on GEDCOMReader.py
> +            death_date = datetime.strptime(individual.death, '%d %b %Y')
here too

2023-08-09 21:38 UTC, Slackow approved these changes

2023-08-10 00:32 UTC, RonnieArvanites approved these changes

2023-08-10 16:14 UTC, merged